// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMU3ixBpG512ppsYQ6jGqaHuLvt_M5IM',
    appId: '1:729373431880:web:f47338afb7b343fa4ca07d',
    messagingSenderId: '729373431880',
    projectId: 'registration-eeac1',
    authDomain: 'registration-eeac1.firebaseapp.com',
    storageBucket: 'registration-eeac1.appspot.com',
    measurementId: 'G-MBHS7QYY9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABbbty3ZkGX5M1fuC0CCi9I4-F4w0Wo-0',
    appId: '1:729373431880:android:b5e4ea4080393cb24ca07d',
    messagingSenderId: '729373431880',
    projectId: 'registration-eeac1',
    storageBucket: 'registration-eeac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwvkjpXgbObrbhXdr8FJOgMqT9MyXlObs',
    appId: '1:729373431880:ios:3ae1a860323c991c4ca07d',
    messagingSenderId: '729373431880',
    projectId: 'registration-eeac1',
    storageBucket: 'registration-eeac1.appspot.com',
    iosBundleId: 'com.example.studentRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwvkjpXgbObrbhXdr8FJOgMqT9MyXlObs',
    appId: '1:729373431880:ios:3ae1a860323c991c4ca07d',
    messagingSenderId: '729373431880',
    projectId: 'registration-eeac1',
    storageBucket: 'registration-eeac1.appspot.com',
    iosBundleId: 'com.example.studentRegistration',
  );
}
